FROM golang:1.15.7-alpine3.13 as builder


RUN apk update && apk add --no-cache git ca-certificates && update-ca-certificates

COPY go.mod .
COPY go.sum .
ENV GOPATH=
RUN go mod download
COPY ./ ./
RUN go build -o main
FROM alpine:3.9

COPY --from=builder /go/main ./
COPY --from=builder /go/db ./db
COPY --from=builder /go/config/service_config.yml ./

ENTRYPOINT ["./main"]